Repository globocom/huskyCI, pull requests merged in 2018-12, with the labels that each got.

#140 [FEAT] Add connection pool
  analysis/huskydb.go
  context/config.go
  db/mongo/db.go
  server.go
Labels: refact

#143 [DOCS] Add license to HuskyCI project
  LICENSE.md
  README.md
  analysis/analysis.go
  analysis/bandit.go
  analysis/brakeman.go
  analysis/dockerrun.go
  analysis/enry.go
  analysis/gosec.go
  analysis/huskydb.go
  context/config.go
  db/mongo/db.go
  dockers/api.go
  server.go
  types/types.go
Labels: docs

#144 WIP: Add RetireJS to HuskyCI
  Makefile
  analysis/dockerrun.go
  analysis/gosec.go
  analysis/retirejs.go
  config.yaml
  context/config.go
  dockers/retirejs/Dockerfile
  server.go
Labels: feature, refact

#148 [REFACT] Add glbgelf logger and treat nil cOutput
  analysis/retirejs.go
Labels: refact

#149 [FIX] Add nil output treatment to bandit.go
  analysis/bandit.go
Labels: bug

#151 Refactor glbgelf using a new log package
  Makefile
  analysis/analysis.go
  analysis/bandit.go
  analysis/brakeman.go
  analysis/dockerrun.go
  analysis/enry.go
  analysis/gosec.go
  analysis/huskydb.go
  analysis/retirejs.go
  context/config.go
  db/mongo/db.go
  dockers/api.go
  log/log.go
  log/messagecodes.go
  server.go
Labels: refact

#154 [FIX] Refactor code to use log package
  analysis/brakeman.go
Labels: bug, refact
