Repository globocom/huskyCI, pull requests merged in 2019-07, with the labels that each got.

#278 Fix container name conflicts
  api/dockers/api.go
  api/util/util.go
  api/util/util_test.go
Labels: fix

#277 Adjust securitytests Dockerfiles
  deployments/dockerfiles/bandit/2.7/Dockerfile
  deployments/dockerfiles/bandit/Dockerfile
  deployments/dockerfiles/enry/Dockerfile
Labels: fix

#275 Add JSON output option to huskyCI client
  Makefile
  client/analysis/analysis.go
  client/analysis/output.go
  client/cmd/main.go
  client/types/types.go
Labels: feature, hackday, refact

#281 Add new release into context functions
  api/context/context.go
Labels: feature

#282 Modify Safety output to be more verbose
  api/analysis/safety.go
  client/analysis/output.go
Labels: fix

#283 Increase client tick time
  client/analysis/analysis.go
Labels: refact

#284 Handle when Safety fails to run and adjust it's output to be more verbose
  api/analysis/safety.go
  api/config.yaml
  client/analysis/output.go
  client/util/util.go
Labels: fix

#285 Add run-client-linux-json function into Makefile
  Makefile
Labels: feature

#287 Adjust retireJS struct to fit new output
  api/analysis/retirejs.go
Labels: fix

#288 Add support for RetireJS to install internal dependencies
  api/analysis/analysis.go
  api/config.yaml
  api/db/huskydb.go
  api/dockers/api.go
  api/log/messagecodes.go
  api/routes/analysis.go
  api/types/types.go
  api/util/util.go
  api/util/util_test.go
  client/analysis/analysis.go
  client/analysis/output.go
  client/config/config.go
  client/types/types.go
Labels: feature

#289 [FEAT] Add project info into client's JSON output
  client/analysis/analysis.go
  client/types/types.go
Labels: feature

#291 Fix retireJS not writing cResult and cInfo in the database in case of success
  api/analysis/retirejs.go
Labels: fix

#295 Add tsuru.yml into huskyCI repository
  tsuru.yml
Labels: feature

#294 Add new release (v.0.5.0) into context functions
  api/context/context.go
Labels: feature

#296 Fix mongoDB not updating if internaldepURL changes
  api/db/huskydb.go
  api/log/messagecodes.go
  api/routes/analysis.go
  api/types/types.go
Labels: fix

#299 Add npm audit security test into huskyCI
  Makefile
  README.md
  api/analysis/dockerrun.go
  api/analysis/npmaudit.go
  api/config.yaml
  api/context/context.go
  api/log/messagecodes.go
  api/util/api/api-util.go
  client/analysis/output.go
  client/types/npmaudit.go
  client/types/types.go
  deployments/dockerfiles/npmaudit/Dockerfile
Labels: feature

#301 Remove empty output from retireJS
  client/analysis/output.go
Labels: fix

#302 Update security tests each time huskyCI starts
  api/util/api/api-util.go
Labels: feature

#298 Remove duplicated retireJS vulnerabilities
  client/analysis/output.go
  client/types/types.go
  client/util/util.go
Labels: feature

#303 Update sec tests insertion logic
  api/db/huskydb.go
  api/log/messagecodes.go
  api/util/api/api-util.go
Labels: fix

#304 Add new release into context
  api/context/context.go
Labels: feature

#306 Refactoring Repository and Analysis structs
  api/analysis/analysis.go
  api/analysis/enry.go
  api/db/huskydb.go
  api/routes/analysis.go
  api/types/types.go
  api/util/util.go
Labels: refact

#311 Introduction of tests and code coverage
  .circleci/config.yml
  Gopkg.lock
  Makefile
  api/server.go
  api/util/api/api.go
  api/util/api/api_suite_test.go
  api/util/api/api_test.go
  api/util/api/types.go
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/common.go
  vendor/github.com/davecgh/go-spew/spew/config.go
  vendor/github.com/davecgh/go-spew/spew/doc.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/spew.go
  vendor/github.com/fatih/color/.travis.yml
  vendor/github.com/fatih/color/Gopkg.lock
  vendor/github.com/fatih/color/Gopkg.toml
  vendor/github.com/fatih/color/LICENSE.md
  vendor/github.com/fatih/color/README.md
  vendor/github.com/fatih/color/color.go
  vendor/github.com/fatih/color/doc.go
  vendor/github.com/hpcloud/tail/.travis.yml
  vendor/github.com/hpcloud/tail/README.md
  vendor/github.com/hpcloud/tail/ratelimiter/memory.go
  vendor/github.com/hpcloud/tail/tail.go
  vendor/github.com/hpcloud/tail/watch/filechanges.go
  vendor/github.com/hpcloud/tail/watch/inotify.go
  vendor/github.com/hpcloud/tail/watch/inotify_tracker.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/.editorconfig
  vendor/gopkg.in/fsnotify/fsnotify.v1/.gitignore
  vendor/gopkg.in/fsnotify/fsnotify.v1/.travis.yml
  vendor/gopkg.in/fsnotify/fsnotify.v1/AUTHORS
  vendor/gopkg.in/fsnotify/fsnotify.v1/CHANGELOG.md
  vendor/gopkg.in/fsnotify/fsnotify.v1/CONTRIBUTING.md
  vendor/gopkg.in/fsnotify/fsnotify.v1/LICENSE
  vendor/gopkg.in/fsnotify/fsnotify.v1/README.md
  vendor/gopkg.in/fsnotify/fsnotify.v1/fen.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/fsnotify.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/inotify.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/inotify_poller.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/kqueue.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/open_mode_bsd.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/open_mode_darwin.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/windows.go
Labels: feature, refact

#313 Fix coverage
  .circleci/config.yml
  Makefile
  README.md
Labels: feature, refact

#308 Add vulnerabilities into Analysis struct
  api/analysis/analysis.go
  api/analysis/bandit.go
  api/analysis/brakeman.go
  api/analysis/dockerrun.go
  api/analysis/enry.go
  api/analysis/gosec.go
  api/analysis/npmaudit.go
  api/analysis/retirejs.go
  api/analysis/safety.go
  api/routes/analysis.go
  api/types/types.go
  api/util/util.go
  client/analysis/output.go
Labels: feature, refact

#317 [FIX] Define dockerd initialization to avoid flag collisions with daemon.json
  deployments/docker-compose.yml
Labels: fix
