Repository globocom/huskyCI, pull requests merged in 2019-06, with the labels that each got.

#247 Add a missing validation for "ERROR_RUNNING_RETIREJS"
  api/config.yaml
  client/analysis/output.go
Labels: fix

#249 Add a verbose text when retireJS fails to run
  client/analysis/output.go
Labels: refact

#250 api|FEAT: Add kill containers logic
  api/analysis/dockerrun.go
  api/context/context.go
  api/dockers/api.go
  api/log/messagecodes.go
  api/util/api/api-util.go
Labels: feature

#253 Create API certificates from environment variables
  api/util/api/api-util.go
Labels: refact

#255 Update Dockerfile commands of enry and gosec
  deployments/dockerfiles/enry/Dockerfile
  deployments/dockerfiles/gosec/Dockerfile
Labels: fix

#261 api|FIX: Add kill containers log
  api/analysis/dockerrun.go
  api/log/messagecodes.go
Labels: fix

#260 Adjust huskyCI to contemplate RetireJS new output format
  api/analysis/retirejs.go
  api/config.yaml
  client/analysis/output.go
  client/types/retirejs.go
Labels: fix

#262 api|REFACT: Change timeout period to 90 minutes in MonitorAnalysis
  api/analysis/analysis.go
Labels: refact

#264 api|TEST: Add test for CreateContainerName function in package util
  .circleci/config.yml
  Makefile
  api/util/util.go
  api/util/util_suite_test.go
  api/util/util_test.go
Labels: test

#265 Add more tests into util package (HandleCmd function)
  api/util/util.go
  api/util/util_test.go
Labels: test

#266 api|REFACT: Remove RequestResponse util function
  api/routes/analysis.go
  api/routes/repository.go
  api/routes/securitytest.go
  api/util/util.go
Labels: refact

#257 Add Linux install instructions
  Makefile
  README.md
Labels: docs, refact

#267 Fix Docker-Compose version issue
  Makefile
  deployments/scripts/generate-env-pass.sh
  deployments/scripts/generate-env.sh
  deployments/scripts/run-create-certs.sh
Labels: fix, refact

#269 deployments|FIX: Change single for double quotes
  deployments/scripts/generate-env.sh
Labels: fix

#270 Adjust Safety commands and scripts
  api/config.yaml
  deployments/dockerfiles/safety/Dockerfile
  deployments/dockerfiles/safety/script.sh
Labels: fix

#268 Add all package util tests
  api/util/util.go
  api/util/util_test.go
Labels: test
