Repository globocom/huskyCI, pull requests merged in 2019-09, with the labels that each got.

#340 Add #nohusky tag to Bandit security test
  api/securitytest/bandit.go
  api/securitytest/run.go
  api/types/types.go
  api/util/util.go
  api/util/util_test.go
  client/analysis/output.go
  client/types/types.go
Labels: feature

#343 Move API binary to root's folder
  Makefile
Labels: refact

#342 Add method to handle the '#nohusky' tag validation
  api/securitytest/bandit.go
  api/util/util.go
  api/util/util_test.go
Labels: refact

#345 Add Tsuru env var into Procfile to fix exec error
  Procfile
Labels: fix

#346 Revert Makefile and Procfile changes
  Makefile
  Procfile
Labels: fix

#348 Add huskyCI API stats routes
  api/db/huskystats.go
  api/db/mongo/mongo.go
  api/log/messagecodes.go
  api/routes/stats.go
  api/server.go
  api/util/util.go
Labels: feature

#349 Fix HuskyCI API stats time range intervals
  api/db/huskystats.go
Labels: fix

#350 Replace "success" to "passed" into cResult
  api/securitytest/run.go
  api/securitytest/securitytest.go
Labels: refact

#351 Security tests now run in parallel
  api/securitytest/run.go
Labels: feature

#353 FIX gitauthors - commit author extraction
  api/config.yaml
Labels: fix

#354 Fix HuskyCI execution should fail gracefully
  api/analysis/analysis.go
  api/config.yaml
  api/dockers/huskydocker.go
  api/routes/analysis.go
  api/securitytest/run.go
  api/securitytest/securitytest.go
  api/securitytest/yarnaudit.go
  api/types/types.go
  client/analysis/analysis.go
  client/types/types.go
Labels: fix

#355 Add CORS configuration into API
  api/context/context.go
  api/context/context_test.go
  api/server.go
  api/util/api/api.go
  deployments/docker-compose.yml
Labels: feature

#356 Fix all javascript analyses returning warning
  api/securitytest/run.go
Labels: fix

#357 Remove container from Docker API when it finishes
  api/dockers/huskydocker.go
  api/log/messagecodes.go
Labels: feature

#358 Add configuration to set securityTest's containers tag
  api/config.yaml
  api/context/context.go
  api/context/context_test.go
  api/dockers/huskydocker.go
  api/securitytest/securitytest.go
  api/types/types.go
  client/analysis/analysis.go
  client/analysis/output.go
  client/types/types.go
Labels: feature

#359 Add FE service into docker compose
  README.md
  deployments/docker-compose.yml
Labels: feature

#360 Add Black Hat Arsenal Europe 2019 tag
  README.md
Labels: docs, feature

#361 Fix yarnaudit execution and output too large
  api/config.yaml
  api/securitytest/securitytest.go
  api/securitytest/yarnaudit.go
  client/analysis/output.go
Labels: fix

#364 Severity stats route
  api/db/huskystats.go
  api/routes/stats.go
Labels: feature
