Repository globocom/huskyCI, pull requests merged in 2019-08, with the labels that each got.

#319 Token generation and validation
  Gopkg.lock
  api/auth/authmongo_test.go
  api/auth/pbkdf2caller.go
  api/auth/types.go
  api/db/huskydb.go
  api/db/mongo/mongo.go
  api/log/messagecodes.go
  api/routes/analysis.go
  api/routes/token.go
  api/server.go
  api/token/generator.go
  api/token/token.go
  api/token/token_suite_test.go
  api/token/token_test.go
  api/token/tokenvalidator.go
  api/token/tokenvalidator_test.go
  api/token/types.go
  api/types/types.go
  api/util/util.go
  vendor/github.com/google/uuid/.travis.yml
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/CONTRIBUTORS
  vendor/github.com/google/uuid/LICENSE
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/doc.go
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/util.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
Labels: feature, refact

#322 Add license into files
  api/auth/auth.go
  api/auth/auth_suite_test.go
  api/auth/auth_test.go
  api/auth/authmongo.go
  api/auth/authmongo_test.go
  api/auth/pbkdf2caller.go
  api/auth/types.go
  api/log/log.go
  api/log/messagecodes.go
  api/routes/analysis.go
  api/routes/healthcheck.go
  api/routes/repository.go
  api/routes/routes_suite_test.go
  api/routes/securitytest.go
  api/routes/token.go
  api/routes/user.go
  api/routes/version.go
  api/routes/version_test.go
  api/security/security.go
  api/token/generator.go
  api/token/token.go
  api/token/token_suite_test.go
  api/token/token_test.go
  api/token/tokenvalidator.go
  api/token/tokenvalidator_test.go
  api/token/types.go
  api/user/user.go
  api/util/util.go
  api/util/util_suite_test.go
  api/util/util_test.go
  client/types/bandit.go
  client/util/util.go
  deployments/scripts/create-certs.sh
  deployments/scripts/generate-env.sh
  deployments/scripts/run-create-certs.sh
Labels: docs

#323 Add rm .env and adjust header
  deployments/scripts/create-certs.sh
  deployments/scripts/generate-env.sh
  deployments/scripts/run-create-certs.sh
Labels: fix

#324 Add Husky-Token logic into client
  Makefile
  README.md
  client/analysis/analysis.go
  client/config/config.go
  deployments/scripts/generate-env.sh
  deployments/scripts/generate-local-token.sh
Labels: feature

#326 Check if certs are already there
  deployments/scripts/run-create-certs.sh
Labels: feature

#327 Test context package
  .gitignore
  api/analysis/dockerrun.go
  api/auth/pbkdf2caller.go
  api/auth/types.go
  api/context/context.go
  api/context/context_suite_test.go
  api/context/context_test.go
  api/context/types.go
  api/db/huskydb.go
  api/dockers/api.go
  api/log/messagecodes.go
  api/routes/analysis.go
  api/routes/token.go
  api/routes/version_test.go
  api/server.go
  api/token/generator.go
  api/token/token.go
  api/token/token_test.go
  api/token/tokenvalidator.go
  api/token/tokenvalidator_test.go
  api/token/types.go
  api/types/types.go
  api/user/user.go
  api/util/api/types.go
Labels: refact

#328 huskyCI mega refactoring (Analysis, SecurityTest, RetireJS, DockerRun)
  Makefile
  README.md
  api/analysis/analysis.go
  api/analysis/bandit.go
  api/analysis/brakeman.go
  api/analysis/dockerrun.go
  api/analysis/enry.go
  api/analysis/gosec.go
  api/analysis/npmaudit.go
  api/analysis/retirejs.go
  api/analysis/safety.go
  api/config.yaml
  api/context/context.go
  api/context/context_test.go
  api/db/huskydb.go
  api/dockers/api.go
  api/dockers/huskydocker.go
  api/log/messagecodes.go
  api/routes/analysis.go
  api/routes/repository.go
  api/routes/securitytest.go
  api/security/security.go
  api/securitytest/bandit.go
  api/securitytest/brakeman.go
  api/securitytest/enry.go
  api/securitytest/gosec.go
  api/securitytest/npmaudit.go
  api/securitytest/run.go
  api/securitytest/safety.go
  api/securitytest/securitytest.go
  api/types/types.go
  api/util/api/api.go
  api/util/util.go
  api/util/util_test.go
  client/analysis/analysis.go
  client/analysis/output.go
  client/config/config.go
  client/types/retirejs.go
  client/types/types.go
  client/util/util.go
  deployments/dockerfiles/retirejs/Dockerfile
Labels: refact

#329 Add GitAuthors securityTest
  Makefile
  api/analysis/analysis.go
  api/config.yaml
  api/context/context.go
  api/context/context_test.go
  api/dockers/huskydocker.go
  api/log/messagecodes.go
  api/securitytest/gitauthors.go
  api/securitytest/gosec.go
  api/securitytest/run.go
  api/securitytest/securitytest.go
  api/types/types.go
  api/util/api/api.go
  deployments/dockerfiles/gitauthors/Dockerfile
Labels: feature, fix
