Repository globocom/huskyCI, pull requests merged in 2019-11, with the labels that each got.

#422 Implementation of functions for data inserts and retrieves in PostgreSQL DB
  Makefile
  api/analysis/analysis.go
  api/context/context.go
  api/db/db_suite_test.go
  api/db/huskydb.go
  api/db/jsoncaller.go
  api/db/postgres.go
  api/db/postgres/postgres_handler.go
  api/db/postgres/sql.go
  api/db/postgres/sql_test.go
  api/db/postgres/types.go
  api/db/postgres_test.go
  api/db/psqlretriever.go
  api/db/types.go
  api/types/types.go
  go.mod
  go.sum
Labels: feature, refact

#426 Increase huskyCI's client timeout to 1 hour
  client/analysis/analysis.go
Labels: feature

#428 Run Yarn on root folder only
  api/config.yaml
Labels: refact

#429 Update: Containers, Release and Mods
  api/config.yaml
  api/context/context.go
  api/context/context_test.go
  go.mod
  go.sum
Labels: feature

#431 Change FE docker-compose port
  deployments/docker-compose.yml
Labels: refact

#430 Fix SonarQube empty slice output
  client/integration/sonarqube/sonarqube.go
  client/integration/sonarqube/sonarqube_test.go
  client/integration/sonarqube/testdata/analysis/not_vulnerable_project.json
  client/integration/sonarqube/testdata/sonarqube/not_vulnerable_output.json
Labels: fix

#424 Adjustments to support data storage in Postgres and Postgres container image generation
  api/analysis/analysis.go
  api/context/context.go
  api/db/huskydb.go
  api/db/postgres.go
  api/db/postgres/sql.go
  api/db/postgres_test.go
  api/db/psqlretriever.go
  api/db/types.go
  api/routes/analysis.go
  api/routes/user.go
  api/securitytest/enry.go
  api/securitytest/run.go
  api/securitytest/securitytest.go
  api/types/types.go
  api/util/api/api.go
  deployments/docker-compose.yml
  deployments/dockerfiles/postgres.Dockerfile
  deployments/huskyci.sql
Labels: bug, feature, refact

#425 Pass docker registry address in configuration file
  api/dockers/huskydocker.go
  api/securitytest/securitytest.go
Labels: feature, refact

#432 Include Pipfile support to safety
  api/config.yaml
Labels: feature
