Repository globocom/huskyCI, pull requests merged in 2019-04, with the labels that each got.

#214 Add "cInfo" as an extra field to huskyCI security analyses
  api/analysis/analysis.go
  api/analysis/bandit.go
  api/analysis/brakeman.go
  api/analysis/dockerrun.go
  api/analysis/enry.go
  api/analysis/gosec.go
  api/analysis/retirejs.go
  api/analysis/safety.go
  api/types/types.go
  client/types/types.go
Labels: feature, refact

#213 huskyCI Mega Refactoring (Part 3)
  api/context/config.go
  api/context/context.go
  api/dockers/api.go
  api/log/log.go
  api/log/messagecodes.go
  api/routes/version.go
  api/server.go
  api/util/api/api-util.go
  api/util/util.go
  client/config/config.go
  deployments/docker-compose.yml
  deployments/dockerfiles/api.Dockerfile
  deployments/dockerfiles/bandit/2.7/Dockerfile
  deployments/dockerfiles/bandit/3.6/Dockerfile
  deployments/dockerfiles/brakeman/Dockerfile
  deployments/dockerfiles/db.Dockerfile
  deployments/dockerfiles/enry/Dockerfile
  deployments/dockerfiles/gosec/Dockerfile
  deployments/dockerfiles/retirejs/Dockerfile
  deployments/dockerfiles/safety/Dockerfile
  deployments/dockerfiles/safety/script.sh
  deployments/mongo.Dockerfile
Labels: refact

#216 Fix huskyCI exiting before all containers have finished
  api/analysis/analysis.go
  api/analysis/dockerrun.go
  api/analysis/enry.go
  api/db/huskydb.go
  api/log/messagecodes.go
  api/types/types.go
  client/analysis/output.go
  client/types/types.go
Labels: bug

#223 FIX: GoSec updating wrong info into MongoDB
  api/analysis/gosec.go
Labels: bug

#221 FIX: Adjust branch regexp to avoid unmarshal error
  api/routes/analysis.go
Labels: bug

#224 Add analysis start and finish time
  api/analysis/analysis.go
  api/db/huskydb.go
  api/types/types.go
Labels: feature

#225 Add retireJS params to avoid checking dev deps
  api/config.yaml
Labels: feature

#228 Adjust all API request responses to JSON format
  api/log/messagecodes.go
  api/routes/analysis.go
  api/routes/repository.go
  api/routes/securitytest.go
  client/analysis/analysis.go
  client/types/types.go
Labels: docs, refact

#230 Remove init function from context file
  api/context/context.go
Labels: bug

#234 Fix Safety bug when "requirements.txt" isn't found
  api/config.yaml
  client/analysis/output.go
Labels: fix

#231 Add status code and RID checks in StartAnalysis
  client/analysis/analysis.go
Labels: feature

#236 Add ginkgo tests for routes package
  Makefile
  api/context/context.go
  api/routes/routes_suite_test.go
  api/routes/version.go
  api/routes/version_test.go
Labels: test
