Repository globocom/huskyCI, pull requests merged in 2019-10, with the labels that each got.

#363 Add containers' functions into Makefile and update API and SecurityTests versions
  Makefile
  api/config.yaml
  api/context/context.go
  api/context/context_test.go
  deployments/scripts/build-containers.sh
  deployments/scripts/check-containers-version.sh
  deployments/scripts/create-certs.sh
  deployments/scripts/generate-env.sh
  deployments/scripts/generate-local-token.sh
  deployments/scripts/push-containers.sh
  deployments/scripts/run-create-certs.sh
Labels: feature

#385 Avoid multiples yarn.locks file in YarnAudit Logic
  api/config.yaml
Labels: fix

#386 Replace script.sh into jq instructions to parse Safety's JSON output
  api/config.yaml
  deployments/dockerfiles/safety/Dockerfile
  deployments/dockerfiles/safety/script.sh
Labels: fix

#373 add a simple test to log package
  api/log/log.go
  api/log/log_test.go
Labels: refact

#391 Improvements in code style
  api/analysis/analysis.go
  api/db/mongo/mongo.go
  api/dockers/huskydocker.go
  api/securitytest/enry.go
  api/securitytest/run.go
  api/util/api/api.go
  client/analysis/analysis.go
  client/analysis/output.go
  client/cmd/main.go
  client/config/config.go
Labels: refact

#393 Fix brakeman security test
  api/config.yaml
Labels: fix

#390 Improvements in test coverage
  api/log/log_test.go
Labels: fix

#389 Add Gitleaks securityTest
  README.md
  api/config.yaml
  api/context/context.go
  api/context/context_test.go
  api/log/messagecodes.go
  api/securitytest/gitleaks.go
  api/securitytest/run.go
  api/securitytest/securitytest.go
  api/types/types.go
  api/util/api/api.go
  client/analysis/output.go
  client/types/gitleaks.go
  client/types/types.go
  deployments/dockerfiles/gitleaks/Dockerfile
  deployments/scripts/build-containers.sh
  deployments/scripts/check-containers-version.sh
  deployments/scripts/push-containers.sh
Labels: feature

#396 Fix Lint and Gitleaks
  api/config.yaml
  cli/client/analysis.go
  cli/client/analysis_test.go
  cli/cmd/run.go
  cli/config/config_test.go
  go.mod
  go.sum
Labels: fix

#397 Add missing go get lint install instructions
  Makefile
Labels: fix

#402 Add -c parameter into jq cmd of Safety
  api/config.yaml
Labels: fix

#408 Analysis history stat route
  api/db/huskystats.go
Labels: feature

#410 Fix time range query string parameter
  api/db/huskystats.go
Labels: fix

#412 Fixing tests for api/util/util.go
  api/util/util_test.go
Labels: fix

#413 Remove unused HUSKYCI_DOCKERAPI_CERT_CA env var
  api/util/api/api.go
Labels: refact

#420 gitleaks now ignores testdata and vendor
  .gitleaks.toml
  api/config.yaml
Labels: feature, fix

#421 Add gitleaks to .gitleaks.toml configuration
  .gitleaks.toml
Labels: fix
