Repository globocom/huskyCI, pull requests merged in 2019-12, with the labels that each got.

#434 Ensure js projects have package-lock.json or yarn.lock
  api/config.yaml
Labels: fix

#436 Set Spotbugs as non default securityTest
  api/config.yaml
Labels: fix

#437 Remove JS file from repository
  .gitignore
  Makefile
  deployments/mongo-init.js
  deployments/scripts/generate-local-token.sh
  deployments/scripts/prepare-local-mongodb.sh
Labels: feature

#438 Add error metric to the stats route
  api/db/huskystats.go
Labels: feature

#439 Check only prod dependencies in Yarn Audit
  api/config.yaml
Labels: fix

#442 api|FEAT: Update securityTest containers
  api/config.yaml
Labels: feature

#443 Refactoring environment variables
  api/auth/authmongo_test.go
  api/auth/pbkdf2caller.go
  api/auth/types.go
  api/context/context.go
  api/context/context_test.go
  api/token/token.go
  api/token/token_test.go
  api/user/user.go
  api/util/api/api.go
  deployments/docker-compose.yml
  go.mod
  go.sum
Labels: refact

#444 Add #nohusky tag to Gosec
  api/config.yaml
  api/securitytest/gosec.go
  api/types/types.go
  api/util/util.go
  client/analysis/output.go
Labels: feature

#445 Add new README.md
  README.md
  huskyCI-dashboard.png
  huskyCI-stage.png
Labels: docs
