Repository globocom/huskyCI, pull requests merged in 2019-03, with the labels that each got.

#183 Add the option to use TLS as a feature flag
  api/context/config.go
  api/server.go
  client/analysis/analysis.go
  client/config/config.go
  deployments/scripts/generate-env-pass.sh
  util/util.go
Labels: feature

#204 Change container names to a huskyCI standard
  Makefile
  deployments/docker-compose.yml
  deployments/scripts/create-certs.sh
Labels: refact

#206 Fix ImageIsLoaded wrong parameter being called
  api/analysis/dockerrun.go
Labels: bug

#205 Remove random passwords to boost dev process
  .gitignore
  deployments/api.Dockerfile
  deployments/db.Dockerfile
  deployments/docker-compose.yml
  deployments/mongo-init.js
  deployments/scripts/generate-env-pass.sh
Labels: refact
