Repository globocom/huskyCI, pull requests merged in 2020-01, with the labels that each got.

#450 Add Gitleaks Timeout Logic and fix multiple bugs found
  api/config.yaml
  api/securitytest/enry.go
  api/securitytest/gitleaks.go
  api/securitytest/gosec.go
  api/securitytest/run.go
  api/securitytest/securitytest.go
  client/analysis/output.go
Labels: feature, fix

#453 FIX gitleaks timeout output
  api/config.yaml
Labels: fix

#456 Add a more verbose output to client
  client/cmd/main.go
Labels: feature
